# Generated by Django 2.0 on 2018-05-31 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_availability', models.DateTimeField()),
                ('end_availability', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CurSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(default='yo', max_length=300)),
                ('judgement', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('emotion', models.CharField(blank=True, max_length=5, null=True)),
                ('wrong_indexes', models.CharField(blank=True, max_length=30, null=True)),
                ('correction', models.CharField(blank=True, default='', max_length=300)),
                ('checked_error', models.NullBooleanField()),
                ('try_again', models.NullBooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('learner_emotion', models.CharField(blank=True, max_length=12, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cursentence',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='face.Session'),
        ),
    ]
