# Generated by Django 2.0 on 2019-06-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='transcription',
            new_name='transcriptions',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='transcription',
            new_name='transcriptions',
        ),
    ]
