# Generated by Django 2.2.3 on 2019-07-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioErrorCorrectionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='')),
                ('transcript', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.CharField(blank=True, max_length=5000, null=True)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.AudioErrors')),
            ],
        ),
    ]
