# Generated by Django 2.0 on 2019-10-10 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermSentence',
            new_name='Sentence',
        ),
        migrations.RemoveField(
            model_name='tempsentence',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='tempsentence',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='tempsentence',
            name='p_sentence',
        ),
        migrations.DeleteModel(
            name='TempSentence',
        ),
    ]
