# Generated by Django 2.0 on 2019-07-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioErrors',
            new_name='AudioError',
        ),
        migrations.RenameModel(
            old_name='PostTalkTimings',
            new_name='PostTalkTiming',
        ),
    ]
