# Generated by Django 2.2.3 on 2019-07-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.SmallIntegerField()),
                ('end_index', models.SmallIntegerField()),
                ('intention', models.CharField(max_length=500, null=True)),
                ('typed', models.NullBooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.AudioFile')),
            ],
        ),
        migrations.CreateModel(
            name='AudioErrorAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.CharField(blank=True, max_length=500, null=True)),
                ('correct', models.NullBooleanField()),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.AudioFile')),
            ],
        ),
    ]
