# Generated by Django 2.0.4 on 2019-08-11 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Conversation',
        ),
    ]
