# Generated by Django 2.0 on 2018-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='audio',
            field=models.FileField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
