# Generated by Django 2.0 on 2019-10-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20191010_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.RemoveField(
            model_name='posttalktiming',
            name='sentence',
        ),
        migrations.DeleteModel(
            name='PostTalkTiming',
        ),
    ]
