# Generated by Django 2.0.4 on 2019-09-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20190811_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permsentence',
            name='question',
        ),
        migrations.RemoveField(
            model_name='tempsentence',
            name='question',
        ),
        migrations.AlterField(
            model_name='permsentence',
            name='correction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='permsentence',
            name='nodAmount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='permsentence',
            name='nodSpeed',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='permsentence',
            name='prompt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='permsentence',
            name='sentence',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='permsentence',
            name='surprise',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='correction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='judgement',
            field=models.CharField(blank=True, choices=[('C', 'correct'), ('B', 'better'), ('P', 'prompt'), ('M', 'mean_by'), ('I', 'incorrect'), ('D', 'dunno'), ('3', 'more_than_three')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='nodAmount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='nodSpeed',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='prompt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='sentence',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='surprise',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
