# Generated by Django 2.0 on 2019-07-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20190604_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='transcriptions',
            new_name='alternatives',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='transcriptions',
            new_name='alternatives',
        ),
    ]
