# Generated by Django 2.2.3 on 2019-07-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_audioerrorattempt_audioerrors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioerrors',
            name='end_index',
        ),
    ]
