# Generated by Django 2.0.2 on 2018-06-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20180616_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='judgement',
            field=models.CharField(blank=True, choices=[('C', 'correct'), ('B', 'better'), ('M', 'mean_by'), ('I', 'incorrect'), ('D', 'dunno')], max_length=1, null=True),
        ),
    ]
