# Generated by Django 2.0.4 on 2019-09-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20190906_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsentence',
            name='prompt_created',
            field=models.NullBooleanField(),
        ),
    ]
