# Generated by Django 2.0 on 2019-10-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20191010_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='tutorial',
        ),
    ]
