# Generated by Django 2.2.3 on 2019-07-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_remove_audioerrors_end_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioerrorattempt',
            name='error',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.AudioErrors'),
        ),
    ]
