# Generated by Django 2.0.2 on 2018-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_auto_20180622_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='emotion',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
