# Generated by Django 2.0.4 on 2019-09-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_tempsentence_prompt_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsentence',
            name='for_prompt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
