# Generated by Django 2.0 on 2019-10-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_remove_conversation_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='for_prompt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
