# Generated by Django 2.0 on 2019-10-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_sentence_for_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='score',
        ),
    ]
