# Generated by Django 2.0 on 2018-07-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_auto_20180622_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='wrong_indexes',
            new_name='indexes',
        ),
        migrations.AddField(
            model_name='sentence',
            name='prompt',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
