# Generated by Django 2.0.4 on 2019-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_tempsentence_for_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsentence',
            name='prompt_created',
        ),
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
