# Generated by Django 2.0 on 2018-07-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_auto_20180710_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
