# Generated by Django 2.0 on 2019-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_remove_conversation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='final_emotion',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
