# Generated by Django 2.0 on 2019-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0007_auto_20191105_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='loop',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
