# Generated by Django 2.0.4 on 2019-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0007_auto_20190924_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permsentence',
            name='nod_shake',
            field=models.CharField(default='[0, 0]', max_length=30),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='nod_shake',
            field=models.CharField(default='[0, 0]', max_length=30),
        ),
    ]
