# Generated by Django 2.0.2 on 2018-07-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0007_auto_20180710_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='correction',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
