# Generated by Django 2.0.4 on 2019-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_auto_20190924_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permsentence',
            name='emotion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='permsentence',
            name='nod_shake',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='emotion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='nod_shake',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
