# Generated by Django 2.0 on 2018-07-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_auto_20180714_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='checked_error',
            new_name='whats_wrong',
        ),
    ]
