# Generated by Django 2.0 on 2019-11-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_sentence_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spectrospin',
            field=models.BooleanField(default=False),
        ),
    ]
