# Generated by Django 2.0.4 on 2019-09-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0009_auto_20190924_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permsentence',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='permsentence',
            name='correction_timestamp',
        ),
        migrations.RemoveField(
            model_name='permsentence',
            name='prompt_timestamp',
        ),
        migrations.RemoveField(
            model_name='tempsentence',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='tempsentence',
            name='correction_timestamp',
        ),
        migrations.RemoveField(
            model_name='tempsentence',
            name='prompt_timestamp',
        ),
    ]
