# Generated by Django 2.0 on 2019-11-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0009_profile_spectrospin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
