# Generated by Django 2.0.2 on 2018-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0009_auto_20180716_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='whats_wrong_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
