# Generated by Django 2.0.4 on 2019-09-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0010_auto_20190925_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permsentence',
            name='surprise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='tempsentence',
            name='surprise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
