# Generated by Django 2.0 on 2019-11-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0010_auto_20191114_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('visemes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('visemes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('visemes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPhrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('texts', models.CharField(blank=True, max_length=500, null=True)),
                ('urls', models.CharField(blank=True, max_length=500, null=True)),
                ('visemes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='prompt',
            new_name='correction',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='judgement',
            field=models.CharField(blank=True, choices=[('B', 'better'), ('P', 'prompt'), ('M', 'mean_by'), ('I', 'incorrect'), ('D', 'dunno'), ('3', 'more_than_three')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='prompt0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='face.Prompt0'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='prompt1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='face.Prompt1'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='prompt2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='face.Prompt2'),
        ),
    ]
