# Generated by Django 2.0 on 2019-11-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0010_auto_20191114_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('urls', models.CharField(blank=True, max_length=100, null=True)),
                ('visemes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('urls', models.CharField(blank=True, max_length=100, null=True)),
                ('visemes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('urls', models.CharField(blank=True, max_length=100, null=True)),
                ('visemes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPhrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('urls', models.CharField(blank=True, max_length=100, null=True)),
                ('visemes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
