# Generated by Django 2.0 on 2019-11-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0011_prompt0_prompt1_prompt2_stockphrases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt0',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prompt1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prompt2',
            name='id',
        ),
        migrations.AddField(
            model_name='prompt0',
            name='sentence',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='face.Sentence'),
        ),
        migrations.AddField(
            model_name='prompt1',
            name='sentence',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='face.Sentence'),
        ),
        migrations.AddField(
            model_name='prompt2',
            name='sentence',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='face.Sentence'),
        ),
    ]
