# Generated by Django 2.0.4 on 2019-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0011_auto_20190925_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
