# Generated by Django 2.0 on 2018-07-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0011_auto_20180721_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='nod',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sentence',
            name='nodAmount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='surprise',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
