# Generated by Django 2.0 on 2019-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0011_auto_20191123_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='awaiting_next_prompt',
            field=models.NullBooleanField(default=False),
        ),
    ]
