# Generated by Django 2.0 on 2018-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0012_auto_20180723_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='nodSpeed',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='surprise',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
