# Generated by Django 2.0 on 2019-11-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0012_auto_20191122_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt0',
            old_name='urls',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='prompt1',
            old_name='urls',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='prompt2',
            old_name='urls',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='stockphrases',
            old_name='text',
            new_name='texts',
        ),
    ]
