# Generated by Django 2.0 on 2019-11-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0012_sentence_awaiting_next_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('visemes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='prompt0',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='prompt1',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='prompt2',
        ),
        migrations.AlterField(
            model_name='stockphrases',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Prompt0',
        ),
        migrations.DeleteModel(
            name='Prompt1',
        ),
        migrations.DeleteModel(
            name='Prompt2',
        ),
        migrations.AddField(
            model_name='prompt',
            name='sentences',
            field=models.ManyToManyField(to='face.Sentence'),
        ),
    ]
