# Generated by Django 2.0.4 on 2019-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0012_auto_20190926_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='learner_emotion',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
