# Generated by Django 2.0 on 2019-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0013_auto_20191126_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='sentences',
        ),
        migrations.AddField(
            model_name='sentence',
            name='prompts',
            field=models.ManyToManyField(to='face.Prompt'),
        ),
    ]
