# Generated by Django 2.0.4 on 2019-09-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0013_auto_20190928_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='learner_emotion',
            new_name='emotion',
        ),
    ]
