# Generated by Django 2.0 on 2018-07-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0013_auto_20180723_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='correction_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='judgement_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='sentence_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='try_again_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='whats_wrong_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
