# Generated by Django 2.0 on 2018-07-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0014_auto_20180724_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='next_sentence',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sentence',
            name='next_sentence_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='correction_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='judgement_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='try_again_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='whats_wrong_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
