# Generated by Django 2.0.4 on 2019-09-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0014_auto_20190928_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permsentence',
            old_name='session',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='tempsentence',
            old_name='session',
            new_name='conversation',
        ),
    ]
