# Generated by Django 2.0 on 2019-11-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0014_auto_20191126_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='judgement',
            field=models.CharField(blank=True, choices=[('P', 'prompt'), ('M', 'mean_by'), ('I', 'incorrect'), ('D', 'dunno'), ('3', 'more_than_three')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='prompts',
            field=models.ManyToManyField(blank=True, to='face.Prompt'),
        ),
    ]
