# Generated by Django 2.0 on 2019-11-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0015_auto_20191127_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
