# Generated by Django 2.0.2 on 2018-07-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0015_auto_20180726_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='emotion',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
