# Generated by Django 2.0 on 2019-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0016_auto_20191127_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_aud', models.BooleanField(default=False)),
                ('updated_sent', models.BooleanField(default=False)),
                ('audio_ids', models.CharField(blank=True, max_length=30, null=True)),
                ('sentence_ids', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
