# Generated by Django 2.0.2 on 2018-08-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0016_auto_20180730_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='nodAmount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='nodSpeed',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='surprise',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
