# Generated by Django 2.0 on 2019-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0017_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='visemes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
