# Generated by Django 2.0.2 on 2018-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0017_auto_20180806_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='emotion',
            field=models.CharField(default='[0, 0]', max_length=12),
        ),
    ]
