# Generated by Django 2.0 on 2019-12-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0018_auto_20191207_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='url',
            field=models.CharField(max_length=5000),
        ),
    ]
