# Generated by Django 2.0.2 on 2018-08-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0018_auto_20180806_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='show_correction',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sentence',
            name='show_correction_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
