# Generated by Django 2.0 on 2019-12-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0019_auto_20191207_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stockphrases',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockphrases',
            name='texts',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockphrases',
            name='urls',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockphrases',
            name='visemes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
