# Generated by Django 2.0.2 on 2018-08-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0019_auto_20180807_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='question',
            field=models.BooleanField(default=False),
        ),
    ]
