# Generated by Django 2.0 on 2019-12-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0020_auto_20191207_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='visemes',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='stockphrases',
            name='visemes',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
