# Generated by Django 2.0 on 2018-08-27 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face', '0021_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(blank=True, max_length=300, null=True)),
                ('sentence_timestamp', models.DateTimeField(blank=True, null=True)),
                ('question', models.BooleanField(default=False)),
                ('judgement', models.CharField(blank=True, choices=[('C', 'correct'), ('B', 'better'), ('M', 'mean_by'), ('I', 'incorrect'), ('D', 'dunno'), ('3', 'more_than_three')], max_length=1, null=True)),
                ('judgement_timestamp', models.DateTimeField(blank=True, null=True)),
                ('emotion', models.CharField(default='[0, 0]', max_length=12)),
                ('nod', models.NullBooleanField()),
                ('nodSpeed', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('nodAmount', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('surprise', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('indexes', models.CharField(blank=True, max_length=30, null=True)),
                ('correction', models.CharField(blank=True, max_length=300)),
                ('correction_timestamp', models.DateTimeField(blank=True, null=True)),
                ('whats_wrong', models.NullBooleanField()),
                ('whats_wrong_timestamp', models.DateTimeField(blank=True, null=True)),
                ('try_again', models.NullBooleanField()),
                ('try_again_timestamp', models.DateTimeField(blank=True, null=True)),
                ('show_correction', models.NullBooleanField()),
                ('show_correction_timestamp', models.DateTimeField(blank=True, null=True)),
                ('next_sentence', models.NullBooleanField()),
                ('next_sentence_timestamp', models.DateTimeField(blank=True, null=True)),
                ('prompt', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Session')),
            ],
        ),
    ]
