# Generated by Django 2.0 on 2019-12-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0022_auto_20191211_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('texts', models.CharField(blank=True, max_length=1000, null=True)),
                ('urls', models.CharField(blank=True, max_length=1000, null=True)),
                ('visemes', models.CharField(blank=True, max_length=20000, null=True)),
            ],
        ),
    ]
