# Generated by Django 2.0 on 2018-08-28 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0022_permsentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermAudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_to_text', models.CharField(blank=True, max_length=300, null=True)),
                ('audio', models.FileField(upload_to='')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.PermSentence')),
            ],
        ),
        migrations.AddField(
            model_name='audiofile',
            name='speech_to_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
