# Generated by Django 2.0 on 2019-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0023_stockword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockphrases',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='stockphrases',
            name='texts',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='stockphrases',
            name='urls',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='stockword',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
