# Generated by Django 2.0 on 2018-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0023_auto_20180828_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='url',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='permaudiofile',
            name='url',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
