# Generated by Django 2.0 on 2020-01-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0024_auto_20191221_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='visemes',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='stockphrases',
            name='visemes',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
    ]
