# Generated by Django 2.0 on 2018-08-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0024_auto_20180829_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='url',
        ),
        migrations.RemoveField(
            model_name='permaudiofile',
            name='url',
        ),
    ]
