# Generated by Django 2.0 on 2020-01-13 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face', '0025_auto_20200102_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.SmallIntegerField()),
                ('hex', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TiaAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundColour', models.CharField(blank=True, max_length=6)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
