# Generated by Django 2.0 on 2020-01-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0025_auto_20200102_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='device',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='slowFPS',
            field=models.NullBooleanField(),
        ),
    ]
