# Generated by Django 2.0 on 2020-01-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0026_auto_20200113_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='slowFPS',
            new_name='slow_FPS',
        ),
        migrations.AddField(
            model_name='conversation',
            name='slow_FPS_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
