# Generated by Django 2.0 on 2018-09-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0027_auto_20180907_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='living_in_English_speaking_country',
            field=models.BooleanField(default=False),
        ),
    ]
