# Generated by Django 2.0 on 2020-01-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0027_auto_20200115_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
