# Generated by Django 2.0 on 2020-01-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0028_profile_points'),
        ('face', '0027_auto_20200113_1637'),
    ]

    operations = [
    ]
