# Generated by Django 2.0 on 2018-09-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0028_auto_20180907_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='living_in_English_speaking_country',
        ),
        migrations.AddField(
            model_name='profile',
            name='lived_in_english_speaking_country',
            field=models.CharField(choices=[('0', 'never'), ('1', '0-1 year'), ('2', '1-3 years'), ('3', '3-5 years'), ('4', '5-10 years'), ('5', '10+ years')], max_length=1, null=True),
        ),
    ]
