# Generated by Django 2.0 on 2020-01-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0029_merge_20200116_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.SmallIntegerField()),
                ('hair_hex', models.CharField(blank=True, max_length=6)),
                ('brow_hex', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='tiaattributes',
            name='clothesColour',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='userproducts',
            name='clothesColour',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
