# Generated by Django 2.0 on 2018-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0029_auto_20180907_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent',
            field=models.BooleanField(default=True),
        ),
    ]
