# Generated by Django 2.0 on 2020-01-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0030_auto_20200120_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothescolour',
            old_name='brow_hex',
            new_name='hex',
        ),
        migrations.RemoveField(
            model_name='clothescolour',
            name='hair_hex',
        ),
        migrations.RemoveField(
            model_name='clothescolour',
            name='price',
        ),
    ]
