# Generated by Django 2.0 on 2018-10-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0031_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='english_level',
            field=models.CharField(choices=[('0', 'low beginner'), ('1', 'high beginner'), ('2', 'low intermediate'), ('3', 'high intermediate'), ('4', 'low advanced'), ('5', 'high advanced')], max_length=1, null=True),
        ),
    ]
