# Generated by Django 2.0 on 2020-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0031_auto_20200121_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothescolour',
            name='price',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
