# Generated by Django 2.0 on 2020-01-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0032_clothescolour_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.SmallIntegerField()),
                ('hex', models.CharField(blank=True, max_length=6)),
                ('filename', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='tiaattributes',
            name='eyeColour',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
