# Generated by Django 2.0 on 2018-10-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0033_auto_20181021_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permpronunciationrequest',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.PermSentence'),
        ),
    ]
