# Generated by Django 2.0 on 2020-01-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0033_auto_20200121_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='EyeTypes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
