# Generated by Django 2.0 on 2020-01-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0034_userproducts_eyetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundGIF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.SmallIntegerField()),
                ('hex', models.CharField(blank=True, max_length=6)),
                ('filename', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
