# Generated by Django 2.0 on 2018-11-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('face', '0034_auto_20181021_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='avail_group',
            field=models.ManyToManyField(default=3, to='auth.Group'),
        ),
    ]
