# Generated by Django 2.0 on 2020-01-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0035_backgroundgif'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiaattributes',
            name='color_background',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='tiaattributes',
            name='gif_background',
            field=models.CharField(default='None', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userproducts',
            name='gif_backgrounds',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
