# Generated by Django 2.0 on 2020-01-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0036_auto_20200127_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiaattributes',
            name='color_background',
            field=models.NullBooleanField(default=False),
        ),
    ]
