# Generated by Django 2.0 on 2018-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0036_auto_20181111_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='speech_to_text',
            new_name='speech_to_text0',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='speech_to_text',
            new_name='speech_to_text0',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='speech_to_text1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='speech_to_text2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='speech_to_text_conf0',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='speech_to_text_conf1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='speech_to_text_conf2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permaudiofile',
            name='speech_to_text1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='permaudiofile',
            name='speech_to_text2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='permaudiofile',
            name='speech_to_text_conf0',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permaudiofile',
            name='speech_to_text_conf1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permaudiofile',
            name='speech_to_text_conf2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
