# Generated by Django 2.0 on 2020-02-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0037_auto_20200127_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('mobile_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
