# Generated by Django 2.0 on 2018-11-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0037_auto_20181112_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='speech_to_text_conf0',
            new_name='confidence0',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='speech_to_text_conf1',
            new_name='confidence1',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='speech_to_text_conf2',
            new_name='confidence2',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='speech_to_text0',
            new_name='transcription0',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='speech_to_text1',
            new_name='transcription1',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='speech_to_text2',
            new_name='transcription2',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='speech_to_text_conf0',
            new_name='confidence0',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='speech_to_text_conf1',
            new_name='confidence1',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='speech_to_text_conf2',
            new_name='confidence2',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='speech_to_text0',
            new_name='transcription0',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='speech_to_text1',
            new_name='transcription1',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='speech_to_text2',
            new_name='transcription2',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='transcriptionChoicesView',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='permaudiofile',
            name='transcriptionChoicesView',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
