# Generated by Django 2.0 on 2020-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0038_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
