# Generated by Django 2.0 on 2020-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0039_profile_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='enteranceClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('mobile_bool', models.BooleanField(default=False)),
                ('element_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
