# Generated by Django 2.0 on 2018-11-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0039_auto_20181112_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permpronunciationrequest',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='pronunciationrequest',
            name='sentence',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='transcriptionChoicesView',
            new_name='clicks',
        ),
        migrations.RenameField(
            model_name='permaudiofile',
            old_name='transcriptionChoicesView',
            new_name='clicks',
        ),
        migrations.DeleteModel(
            name='PermPronunciationRequest',
        ),
        migrations.DeleteModel(
            name='PronunciationRequest',
        ),
    ]
