# Generated by Django 2.0 on 2018-11-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0040_auto_20181113_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='clicks',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='permaudiofile',
            name='clicks',
            field=models.CharField(default='[]', max_length=2000),
        ),
    ]
