# Generated by Django 2.0 on 2020-02-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0040_enteranceclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enteranceclick',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
