# Generated by Django 2.0 on 2018-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0041_auto_20181113_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='indexes_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='prompt_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
