# Generated by Django 2.0 on 2020-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0041_auto_20200219_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enteranceclick',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
