# Generated by Django 2.0 on 2018-11-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0042_auto_20181122_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='permsentence',
            name='indexes_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permsentence',
            name='prompt_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
