# Generated by Django 2.0 on 2018-12-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0043_auto_20181122_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tutorial_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='judgement',
            field=models.CharField(blank=True, choices=[('C', 'correct'), ('P', 'prompt'), ('B', 'better'), ('M', 'mean_by'), ('I', 'incorrect'), ('D', 'dunno'), ('3', 'more_than_three')], max_length=1, null=True),
        ),
    ]
