# Generated by Django 2.0 on 2018-12-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0044_auto_20181201_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermPostTalkTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startSpeak', models.DateTimeField(null=True)),
                ('finishSpeak', models.DateTimeField(null=True)),
                ('judgementReceivedImmediately', models.DateTimeField(null=True)),
                ('judgementReceivedAfterLeanBack', models.DateTimeField(null=True)),
                ('judgementReceivedBeforeTurningToThink', models.DateTimeField(null=True)),
                ('thoughtBubblesAdded', models.DateTimeField(null=True)),
                ('judgementReceivedInThinkingPos', models.DateTimeField(null=True)),
                ('runAfterJudgement', models.DateTimeField(null=True)),
                ('nodOrShakeHead', models.DateTimeField(null=True)),
                ('prePrepareForPromptSpeech', models.DateTimeField(null=True)),
                ('displaySpeechBubblePrompt', models.DateTimeField(null=True)),
                ('tiaStartTalking', models.DateTimeField(null=True)),
                ('returnToLaptop', models.DateTimeField(null=True)),
                ('initInputReady', models.DateTimeField(null=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.PermSentence')),
            ],
        ),
        migrations.CreateModel(
            name='PostTalkTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startSpeak', models.DateTimeField(null=True)),
                ('finishSpeak', models.DateTimeField(null=True)),
                ('judgementReceivedImmediately', models.DateTimeField(null=True)),
                ('judgementReceivedAfterLeanBack', models.DateTimeField(null=True)),
                ('judgementReceivedBeforeTurningToThink', models.DateTimeField(null=True)),
                ('thoughtBubblesAdded', models.DateTimeField(null=True)),
                ('judgementReceivedInThinkingPos', models.DateTimeField(null=True)),
                ('runAfterJudgement', models.DateTimeField(null=True)),
                ('nodOrShakeHead', models.DateTimeField(null=True)),
                ('prePrepareForPromptSpeech', models.DateTimeField(null=True)),
                ('displaySpeechBubblePrompt', models.DateTimeField(null=True)),
                ('tiaStartTalking', models.DateTimeField(null=True)),
                ('returnToLaptop', models.DateTimeField(null=True)),
                ('initInputReady', models.DateTimeField(null=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Sentence')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='tutorial_complete',
            field=models.BooleanField(default=False),
        ),
    ]
