# Generated by Django 2.0 on 2020-03-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0044_waitingclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='awaiting_next_prompt',
            field=models.NullBooleanField(),
        ),
    ]
