# Generated by Django 2.0 on 2018-12-06 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0045_auto_20181206_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='permposttalktimings',
            name='clickNextSentenceBtn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='permposttalktimings',
            name='clickOptionBtn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='permposttalktimings',
            name='clickShowCorrectionBtn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='permposttalktimings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permposttalktimings',
            name='showOptionBtns',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='permposttalktimings',
            name='turnToBoardToShowErrors',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='posttalktimings',
            name='clickNextSentenceBtn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='posttalktimings',
            name='clickOptionBtn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='posttalktimings',
            name='clickShowCorrectionBtn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='posttalktimings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posttalktimings',
            name='showOptionBtns',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='posttalktimings',
            name='turnToBoardToShowErrors',
            field=models.DateTimeField(null=True),
        ),
    ]
