# Generated by Django 2.0 on 2018-12-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0049_auto_20181208_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='microphone',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sound',
            field=models.NullBooleanField(),
        ),
    ]
