# Generated by Django 2.0 on 2018-12-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0050_auto_20181209_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
