# Generated by Django 2.0 on 2018-12-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0051_session_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permsentence',
            name='judgement',
            field=models.CharField(blank=True, choices=[('C', 'correct'), ('B', 'better'), ('P', 'prompt'), ('M', 'mean_by'), ('I', 'incorrect'), ('D', 'dunno'), ('3', 'more_than_three')], max_length=1, null=True),
        ),
    ]
