# Generated by Django 2.0 on 2019-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0053_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='stage',
        ),
        migrations.AddField(
            model_name='test',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
