# Generated by Django 2.0 on 2019-02-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0054_auto_20190205_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='confidence0',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='confidence1',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='confidence2',
        ),
        migrations.RemoveField(
            model_name='permaudiofile',
            name='confidence0',
        ),
        migrations.RemoveField(
            model_name='permaudiofile',
            name='confidence1',
        ),
        migrations.RemoveField(
            model_name='permaudiofile',
            name='confidence2',
        ),
    ]
