# Generated by Django 2.0 on 2019-03-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0055_auto_20190227_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permsentence',
            name='indexes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='indexes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
